### ISSUE TITLE
package.json found error

### ISSUE THREAD

**Issue by SCWR** [SanderRonde/prettier-plugin-sort-imports#10]
["ERROR" - 14:30:01] ENOENT: no such file or directory, open '/package.json'
Error: ENOENT: no such file or directory, open '/package.json'
    at Object.openSync (node:fs:605:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:473:35)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:2:9462)
    at Z (/Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier-plugin-sort-imports@1.8.0_typescript@5.3.3/node_modules/prettier-plugin-sort-imports/dist/index.js:1:4312)
    at F (/Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier-plugin-sort-imports@1.8.0_typescript@5.3.3/node_modules/prettier-plugin-sort-imports/dist/index.js:1:5168)
    at he (/Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier-plugin-sort-imports@1.8.0_typescript@5.3.3/node_modules/prettier-plugin-sort-imports/dist/index.js:6:590)
    at Object.S [as preprocess] (/Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier-plugin-sort-imports@1.8.0_typescript@5.3.3/node_modules/prettier-plugin-sort-imports/dist/index.js:6:731)
    at parse (file:///Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/index.mjs:19358:43)
    at async coreFormat (file:///Users/cwr/dsky/fanbook_web/node_modules/.pnpm/prettier@3.1.1/node_modules/prettier/index.mjs:20683:7)
["INFO" - 14:30:01] Formatting completed in 5ms.

**Comment by SanderRonde** [comment]
Thanks for the report! Will fix in the next release
